# Generated by Django 3.2.3 on 2023-08-01 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveSmallIntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ME_code', models.CharField(max_length=15)),
                ('area', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.area')),
            ],
        ),
        migrations.CreateModel(
            name='Main_Equipment_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device', models.CharField(default='i3ch', max_length=20)),
                ('Main_Equipment', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.main_equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MEDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MED_mother', models.CharField(default='i3ch', max_length=25)),
                ('MED', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.main_equipment_device')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('manager', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'superadmin'), (2, 'admin'), (3, 'employee'), (4, 'viewer')], default=4)),
                ('occupation', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.occupation')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default='i3ch', max_length=30)),
                ('MEDM', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.medm')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='zone',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.zone'),
        ),
    ]
