# Generated by Django 3.2.3 on 2023-08-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20230801_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.zone'),
        ),
    ]
