# Generated by Django 3.2.3 on 2023-08-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_alter_area_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.zone'),
        ),
        migrations.AlterField(
            model_name='main_equipment',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.area'),
        ),
        migrations.AlterField(
            model_name='main_equipment_device',
            name='Main_Equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.main_equipment'),
        ),
        migrations.AlterField(
            model_name='medm',
            name='MED',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.main_equipment_device'),
        ),
        migrations.AlterField(
            model_name='part',
            name='MEDM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.medm'),
        ),
    ]
