# Generated by Django 3.2.3 on 2023-08-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_auto_20230801_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_equipment_device',
            old_name='Main_Equipment',
            new_name='main_equipment',
        ),
        migrations.RenameField(
            model_name='medm',
            old_name='MED',
            new_name='med',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='MEDM',
            new_name='medm',
        ),
    ]
