# Generated by Django 3.2.3 on 2023-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='assem', max_length=10),
        ),
    ]
