# Generated by Django 3.2.3 on 2023-08-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Assem', 'Assem'), ('Part', 'Part'), ('Zone', 'Zone'), ('Area', 'Area'), ('ME', 'ME'), ('MED', 'MED'), ('MEDM', 'MEDM')], default='assem', max_length=10),
        ),
    ]
