# Generated by Django 3.2.3 on 2023-08-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0012_auto_20230808_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
