# Generated by Django 3.2.3 on 2023-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
