# Generated by Django 4.2.5 on 2023-09-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0016_category_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='drawn',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
