# Generated by Django 4.2.5 on 2023-09-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0018_category_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approve',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
