# Generated by Django 3.2.3 on 2023-09-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0018_remove_category_drawn'),
        ('coding', '0019_category_approve'),
    ]

    operations = [
    ]
