# Generated by Django 3.2.3 on 2023-09-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0020_merge_20230925_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='drawn',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
