# Generated by Django 3.2.3 on 2023-08-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='corporation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.corporation'),
        ),
    ]
