# Generated by Django 3.2.3 on 2023-08-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_occupation_corporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.occupation'),
        ),
    ]
